---
server:
    install: '1'
    packages: [git, vim, nodejs, htop]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: xenial64, hostname: ansible, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: '0' }
